# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ass930085\Downloads\PROXI\Mainwindow\cdtcs_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID85(object):
    def setupUi(self, Form_SID85):
        Form_SID85.setObjectName("Form_SID85")
        Form_SID85.resize(770, 528)
        Form_SID85.setMinimumSize(QtCore.QSize(400, 400))
        self.label_status = QtWidgets.QLabel(Form_SID85)
        self.label_status.setGeometry(QtCore.QRect(10, 410, 741, 101))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.layoutWidget = QtWidgets.QWidget(Form_SID85)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 741, 361))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.checkBox_suppressposmsg = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_suppressposmsg.setObjectName("checkBox_suppressposmsg")
        self.gridLayout.addWidget(self.checkBox_suppressposmsg, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 10, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout.addWidget(self.pushButton_clearLog, 5, 2, 1, 1)
        self.pushButton_Send85Req = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send85Req.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send85Req.setObjectName("pushButton_Send85Req")
        self.gridLayout.addWidget(self.pushButton_Send85Req, 0, 3, 1, 1)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout.addWidget(self.textBrowser_Resp, 10, 1, 1, 2)
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout.addWidget(self.pushButton_appendLog, 5, 3, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 10, 3, 1, 1)
        self.comboBox_DTCSettingType = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_DTCSettingType.setMinimumSize(QtCore.QSize(220, 0))
        self.comboBox_DTCSettingType.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox_DTCSettingType.setObjectName("comboBox_DTCSettingType")
        self.comboBox_DTCSettingType.addItem("")
        self.comboBox_DTCSettingType.addItem("")
        self.gridLayout.addWidget(self.comboBox_DTCSettingType, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout.addWidget(self.label_ResType, 5, 1, 1, 1)
        self.checkBox_DTCOption = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_DTCOption.setMaximumSize(QtCore.QSize(16777215, 20))
        self.checkBox_DTCOption.setObjectName("checkBox_DTCOption")
        self.gridLayout.addWidget(self.checkBox_DTCOption, 1, 0, 2, 1)
        self.lineEdit_DTCSettingInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_DTCSettingInput.setObjectName("lineEdit_DTCSettingInput")
        self.gridLayout.addWidget(self.lineEdit_DTCSettingInput, 2, 1, 1, 3)
        self.pushButton_appendLog.raise_()
        self.label_ResType.raise_()
        self.textBrowser_Resp.raise_()
        self.pushButton_clearLog.raise_()
        self.label.raise_()
        self.pushButton_reset.raise_()
        self.label_3.raise_()
        self.pushButton_Send85Req.raise_()
        self.comboBox_DTCSettingType.raise_()
        self.label_2.raise_()
        self.checkBox_suppressposmsg.raise_()
        self.checkBox_DTCOption.raise_()
        self.lineEdit_DTCSettingInput.raise_()

        self.lineEdit_DTCSettingInput.hide()
        
        self.checkBox_DTCOption.stateChanged.connect(self.toggle_line_edit)

        self.retranslateUi(Form_SID85)
        QtCore.QMetaObject.connectSlotsByName(Form_SID85)
        
      # Function to show/hide lineEdit based on CHECKBOX selection
    def toggle_line_edit(self, state):
        if state == QtCore.Qt.Checked: # Show lineEdit if checked
            self.lineEdit_DTCSettingInput.show()
        else:  # Hide lineEdit if not checked
            self.lineEdit_DTCSettingInput.hide()
    
    def retranslateUi(self, Form_SID85):
        _translate = QtCore.QCoreApplication.translate
        Form_SID85.setWindowTitle(_translate("Form_SID85", "Control DTC Setting 85"))
        self.label_status.setText(_translate("Form_SID85", "No Status"))
        self.checkBox_suppressposmsg.setToolTip(_translate("Form_SID85", "If selected then Suppress Positive Response Message Indication bit will be set in Subfunction"))
        self.checkBox_suppressposmsg.setText(_translate("Form_SID85", "SPRMIB"))
        self.label_3.setText(_translate("Form_SID85", "Response"))
        self.label_2.setText(_translate("Form_SID85", "Response Type"))
        self.pushButton_clearLog.setText(_translate("Form_SID85", "Clear Log"))
        self.pushButton_Send85Req.setToolTip(_translate("Form_SID85", "Sends the 10 service request to ECU"))
        self.pushButton_Send85Req.setText(_translate("Form_SID85", "Send Request"))
        self.pushButton_appendLog.setText(_translate("Form_SID85", "Add to Log"))
        self.pushButton_reset.setText(_translate("Form_SID85", "Reset"))
        self.comboBox_DTCSettingType.setToolTip(_translate("Form_SID85", "Select the  desired DTC Setting Type for ECU to move. If the required setting is not in list then contact admin"))
        self.comboBox_DTCSettingType.setItemText(0, _translate("Form_SID85", "01 - ON"))
        self.comboBox_DTCSettingType.setItemText(1, _translate("Form_SID85", "02 - OFF"))
        self.label.setText(_translate("Form_SID85", "DTC Setting Type"))
        self.label_ResType.setText(_translate("Form_SID85", "No Response"))
        self.checkBox_DTCOption.setText(_translate("Form_SID85", "DTC Setting Control Option Record "))
