# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ass930085\OneDrive - Tata Technologies\Documents\PROXI GIT\reference\ProxiCan\SID_19_16.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID_19_16(object):
    def setupUi(self, Form_SID_19_16):
        Form_SID_19_16.setObjectName("Form_SID_19_16")
        Form_SID_19_16.resize(879, 641)
        self.label_status = QtWidgets.QLabel(Form_SID_19_16)
        self.label_status.setGeometry(QtCore.QRect(10, 550, 851, 71))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.layoutWidget = QtWidgets.QWidget(Form_SID_19_16)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 858, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.subFunction_Name = QtWidgets.QLabel(self.layoutWidget)
        self.subFunction_Name.setObjectName("subFunction_Name")
        self.gridLayout_2.addWidget(self.subFunction_Name, 0, 1, 1, 2)
        self.label_subFunction = QtWidgets.QLabel(self.layoutWidget)
        self.label_subFunction.setObjectName("label_subFunction")
        self.gridLayout_2.addWidget(self.label_subFunction, 0, 0, 1, 1)
        self.checkBox_suppressposmsg = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_suppressposmsg.setObjectName("checkBox_suppressposmsg")
        self.gridLayout_2.addWidget(self.checkBox_suppressposmsg, 0, 3, 1, 1)
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout_2.addWidget(self.pushButton_appendLog, 2, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.pushButton_Send19_16Req = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send19_16Req.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send19_16Req.setObjectName("pushButton_Send19_16Req")
        self.gridLayout_2.addWidget(self.pushButton_Send19_16Req, 0, 4, 1, 1)
        self.DTCEDRN_label = QtWidgets.QLabel(self.layoutWidget)
        self.DTCEDRN_label.setObjectName("DTCEDRN_label")
        self.gridLayout_2.addWidget(self.DTCEDRN_label, 1, 0, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout_2.addWidget(self.pushButton_reset, 5, 4, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DTCEDRN_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.DTCEDRN_lineEdit.setObjectName("DTCEDRN_lineEdit")
        self.horizontalLayout_3.addWidget(self.DTCEDRN_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 1, 1, 4)
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout_2.addWidget(self.label_ResType, 2, 1, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 2, 0, 1, 1)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout_2.addWidget(self.textBrowser_Resp, 5, 1, 1, 3)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout_2.addWidget(self.pushButton_clearLog, 2, 3, 1, 1)

        self.retranslateUi(Form_SID_19_16)
        QtCore.QMetaObject.connectSlotsByName(Form_SID_19_16)

    def retranslateUi(self, Form_SID_19_16):
        _translate = QtCore.QCoreApplication.translate
        Form_SID_19_16.setWindowTitle(_translate("Form_SID_19_16", "Report Mirror Memory DTC Extended Data Record by Record Number 0x16 "))
        self.label_status.setText(_translate("Form_SID_19_16", "No Status"))
        self.subFunction_Name.setText(_translate("Form_SID_19_16", "Report Mirror Memory DTC Extended Data Record by Record Number 0x16 "))
        self.label_subFunction.setText(_translate("Form_SID_19_16", "Sub Function:"))
        self.checkBox_suppressposmsg.setToolTip(_translate("Form_SID_19_16", "If selected then Suppress Positive Response Message Indication bit will be set in Subfunction"))
        self.checkBox_suppressposmsg.setText(_translate("Form_SID_19_16", "SPRMIB"))
        self.pushButton_appendLog.setText(_translate("Form_SID_19_16", "Add to Log"))
        self.label_4.setText(_translate("Form_SID_19_16", "Response : "))
        self.pushButton_Send19_16Req.setToolTip(_translate("Form_SID_19_16", "<html><head/><body><p>Sends the 19 service subfunction 16 request to ECU</p></body></html>"))
        self.pushButton_Send19_16Req.setText(_translate("Form_SID_19_16", "Send Request"))
        self.DTCEDRN_label.setText(_translate("Form_SID_19_16", "DTC Extended Data Record Number:  "))
        self.pushButton_reset.setText(_translate("Form_SID_19_16", "Reset"))
        self.DTCEDRN_lineEdit.setToolTip(_translate("Form_SID_19_16", "<html><head/><body><p>Enter DTC Extended Data Record Number in <span style=\" font-weight:600;\">1-byte hexadecimal format</span></p></body></html>"))
        self.label_ResType.setText(_translate("Form_SID_19_16", "No Response"))
        self.label_5.setText(_translate("Form_SID_19_16", "Response Type: "))
        self.pushButton_clearLog.setText(_translate("Form_SID_19_16", "Clear Log"))
