# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ass930085\OneDrive - Tata Technologies\Documents\PROXI GIT\reference\ProxiCan\SID_3E.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID3E(object):
    def setupUi(self, Form_SID3E):
        Form_SID3E.setObjectName("Form_SID3E")
        Form_SID3E.resize(680, 425)
        Form_SID3E.setMinimumSize(QtCore.QSize(400, 400))
        self.label_status = QtWidgets.QLabel(Form_SID3E)
        self.label_status.setGeometry(QtCore.QRect(10, 340, 661, 71))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.layoutWidget = QtWidgets.QWidget(Form_SID3E)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 661, 302))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 6, 4, 1, 1)
        self.checkBox_suppressposmsg = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_suppressposmsg.setObjectName("checkBox_suppressposmsg")
        self.gridLayout.addWidget(self.checkBox_suppressposmsg, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout.addWidget(self.pushButton_appendLog, 3, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_testerpresent_interval = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_testerpresent_interval.setMinimumSize(QtCore.QSize(113, 20))
        self.lineEdit_testerpresent_interval.setText("")
        self.lineEdit_testerpresent_interval.setObjectName("lineEdit_testerpresent_interval")
        self.gridLayout.addWidget(self.lineEdit_testerpresent_interval, 0, 1, 1, 1)
        self.label_testerpresentinterval = QtWidgets.QLabel(self.layoutWidget)
        self.label_testerpresentinterval.setObjectName("label_testerpresentinterval")
        self.gridLayout.addWidget(self.label_testerpresentinterval, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.pushButton_Stop3EReq = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Stop3EReq.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Stop3EReq.setObjectName("pushButton_Stop3EReq")
        self.gridLayout.addWidget(self.pushButton_Stop3EReq, 0, 4, 1, 1)
        self.pushButton_Send3EReq = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send3EReq.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send3EReq.setObjectName("pushButton_Send3EReq")
        self.gridLayout.addWidget(self.pushButton_Send3EReq, 0, 3, 1, 1)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout.addWidget(self.pushButton_clearLog, 3, 3, 1, 1)
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout.addWidget(self.label_ResType, 3, 1, 1, 2)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout.addWidget(self.textBrowser_Resp, 6, 1, 1, 3)
        self.pushButton_appendLog.raise_()
        self.label_ResType.raise_()
        self.textBrowser_Resp.raise_()
        self.label_testerpresentinterval.raise_()
        self.pushButton_reset.raise_()
        self.label_3.raise_()
        self.pushButton_Stop3EReq.raise_()
        self.label_2.raise_()
        self.checkBox_suppressposmsg.raise_()
        self.lineEdit_testerpresent_interval.raise_()
        self.pushButton_Send3EReq.raise_()
        self.pushButton_clearLog.raise_()

        self.retranslateUi(Form_SID3E)
        QtCore.QMetaObject.connectSlotsByName(Form_SID3E)

    def retranslateUi(self, Form_SID3E):
        _translate = QtCore.QCoreApplication.translate
        Form_SID3E.setWindowTitle(_translate("Form_SID3E", "Tester Present 0x3E"))
        self.label_status.setText(_translate("Form_SID3E", "No Status"))
        self.pushButton_reset.setText(_translate("Form_SID3E", "Reset"))
        self.checkBox_suppressposmsg.setToolTip(_translate("Form_SID3E", "If selected then Suppress Positive Response Message Indication bit will be set in Subfunction"))
        self.checkBox_suppressposmsg.setText(_translate("Form_SID3E", "SPRMIB"))
        self.pushButton_appendLog.setText(_translate("Form_SID3E", "Add to Log"))
        self.label_2.setText(_translate("Form_SID3E", "Response Type"))
        self.lineEdit_testerpresent_interval.setToolTip(_translate("Form_SID3E", "Enter the interval of Tester present request in milliseconds"))
        self.label_testerpresentinterval.setText(_translate("Form_SID3E", "Tester Present Request Interval "))
        self.label_3.setText(_translate("Form_SID3E", "Response"))
        self.pushButton_Stop3EReq.setToolTip(_translate("Form_SID3E", "Stops the periodic 3E service request to ECU"))
        self.pushButton_Stop3EReq.setText(_translate("Form_SID3E", "Stop Request"))
        self.pushButton_Send3EReq.setToolTip(_translate("Form_SID3E", "Sends the 3E service request to ECU"))
        self.pushButton_Send3EReq.setText(_translate("Form_SID3E", "Send Request"))
        self.pushButton_clearLog.setText(_translate("Form_SID3E", "Clear Log"))
        self.label_ResType.setText(_translate("Form_SID3E", "No Response"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SID3E = QtWidgets.QWidget()
    ui = Ui_Form_SID3E()
    ui.setupUi(Form_SID3E)
    Form_SID3E.show()
    sys.exit(app.exec_())