# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ass930085\OneDrive - Tata Technologies\Documents\PROXI GIT\reference\ProxiCan\SID_19_18.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID_19_18(object):
    def setupUi(self, Form_SID_19_18):
        Form_SID_19_18.setObjectName("Form_SID_19_18")
        Form_SID_19_18.resize(875, 630)
        self.layoutWidget = QtWidgets.QWidget(Form_SID_19_18)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 851, 531))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.DTCMaskRecord_label = QtWidgets.QLabel(self.layoutWidget)
        self.DTCMaskRecord_label.setObjectName("DTCMaskRecord_label")
        self.gridLayout_2.addWidget(self.DTCMaskRecord_label, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.DTCSSN_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.DTCSSN_lineEdit.setObjectName("DTCSSN_lineEdit")
        self.horizontalLayout_3.addWidget(self.DTCSSN_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 1, 1, 4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 8, 0, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout_2.addWidget(self.pushButton_reset, 8, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.DTCMaskRecord_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.DTCMaskRecord_lineEdit.setObjectName("DTCMaskRecord_lineEdit")
        self.horizontalLayout.addWidget(self.DTCMaskRecord_lineEdit)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 1, 1, 4)
        self.subFunction_Name = QtWidgets.QLabel(self.layoutWidget)
        self.subFunction_Name.setObjectName("subFunction_Name")
        self.gridLayout_2.addWidget(self.subFunction_Name, 0, 1, 1, 2)
        self.checkBox_suppressposmsg = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_suppressposmsg.setObjectName("checkBox_suppressposmsg")
        self.gridLayout_2.addWidget(self.checkBox_suppressposmsg, 0, 3, 1, 1)
        self.label_subFunction = QtWidgets.QLabel(self.layoutWidget)
        self.label_subFunction.setObjectName("label_subFunction")
        self.gridLayout_2.addWidget(self.label_subFunction, 0, 0, 1, 1)
        self.pushButton_Send19_18Req = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send19_18Req.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send19_18Req.setObjectName("pushButton_Send19_18Req")
        self.gridLayout_2.addWidget(self.pushButton_Send19_18Req, 0, 4, 1, 1)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout_2.addWidget(self.textBrowser_Resp, 8, 1, 1, 3)
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout_2.addWidget(self.pushButton_appendLog, 5, 4, 1, 1)
        self.DTCSSRN_label = QtWidgets.QLabel(self.layoutWidget)
        self.DTCSSRN_label.setObjectName("DTCSSRN_label")
        self.gridLayout_2.addWidget(self.DTCSSRN_label, 2, 0, 1, 1)
        self.label_memsorySelection = QtWidgets.QLabel(self.layoutWidget)
        self.label_memsorySelection.setObjectName("label_memsorySelection")
        self.gridLayout_2.addWidget(self.label_memsorySelection, 3, 0, 1, 1)
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout_2.addWidget(self.label_ResType, 5, 1, 1, 2)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout_2.addWidget(self.pushButton_clearLog, 5, 3, 1, 1)
        self.lineEdit_memorySelection = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_memorySelection.setObjectName("lineEdit_memorySelection")
        self.gridLayout_2.addWidget(self.lineEdit_memorySelection, 3, 1, 1, 4)
        self.label_status = QtWidgets.QLabel(Form_SID_19_18)
        self.label_status.setGeometry(QtCore.QRect(10, 550, 851, 71))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")

        self.retranslateUi(Form_SID_19_18)
        QtCore.QMetaObject.connectSlotsByName(Form_SID_19_18)

    def retranslateUi(self, Form_SID_19_18):
        _translate = QtCore.QCoreApplication.translate
        Form_SID_19_18.setWindowTitle(_translate("Form_SID_19_18", "Report User Defined Memory DTC Snapshot Record By DTC Number 0x18"))
        self.DTCMaskRecord_label.setText(_translate("Form_SID_19_18", "DTC Mask Record:"))
        self.DTCSSN_lineEdit.setToolTip(_translate("Form_SID_19_18", "<html><head/><body><p>Enter DTC Snapshot Record Number in <span style=\" font-weight:600;\">1-byte hexadecimal format</span></p></body></html>"))
        self.label_5.setText(_translate("Form_SID_19_18", "Response Type: "))
        self.label_4.setText(_translate("Form_SID_19_18", "Response : "))
        self.pushButton_reset.setText(_translate("Form_SID_19_18", "Reset"))
        self.DTCMaskRecord_lineEdit.setToolTip(_translate("Form_SID_19_18", "<html><head/><body><p>Enter DTC Mask Record in <span style=\" font-weight:600;\">3-byte hexadecimal format </span></p></body></html>"))
        self.subFunction_Name.setText(_translate("Form_SID_19_18", "Report User Defined Memory DTC Snapshot Record By DTC Number 0x18 "))
        self.checkBox_suppressposmsg.setToolTip(_translate("Form_SID_19_18", "If selected then Suppress Positive Response Message Indication bit will be set in Subfunction"))
        self.checkBox_suppressposmsg.setText(_translate("Form_SID_19_18", "SPRMIB"))
        self.label_subFunction.setText(_translate("Form_SID_19_18", "Sub Function:"))
        self.pushButton_Send19_18Req.setToolTip(_translate("Form_SID_19_18", "<html><head/><body><p>Sends the 19 service subfunction 18 request to ECU</p></body></html>"))
        self.pushButton_Send19_18Req.setText(_translate("Form_SID_19_18", "Send Request"))
        self.pushButton_appendLog.setText(_translate("Form_SID_19_18", "Add to Log"))
        self.DTCSSRN_label.setText(_translate("Form_SID_19_18", "DTC Snapshot Record Number: "))
        self.label_memsorySelection.setText(_translate("Form_SID_19_18", "Memory Selection:"))
        self.label_ResType.setText(_translate("Form_SID_19_18", "No Response"))
        self.pushButton_clearLog.setText(_translate("Form_SID_19_18", "Clear Log"))
        self.lineEdit_memorySelection.setToolTip(_translate("Form_SID_19_18", "<html><head/><body><p>Enter Memory selection in <span style=\" font-weight:600;\">1-byte hexadecimal format</span></p></body></html>"))
        self.label_status.setText(_translate("Form_SID_19_18", "No Status"))
