# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ass930085\OneDrive - Tata Technologies\Documents\PROXI GIT\reference\ProxiCan\SID_28.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID28(object):
    def setupUi(self, Form_SID28):
        Form_SID28.setObjectName("Form_SID28")
        Form_SID28.resize(758, 581)
        self.layoutWidget = QtWidgets.QWidget(Form_SID28)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 10, 681, 451))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_NIN = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_NIN.setObjectName("lineEdit_NIN")
        self.gridLayout.addWidget(self.lineEdit_NIN, 4, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.Communication_type = QtWidgets.QComboBox(self.layoutWidget)
        self.Communication_type.setMinimumSize(QtCore.QSize(220, 0))
        self.Communication_type.setMaximumSize(QtCore.QSize(300, 16777215))
        self.Communication_type.setObjectName("Communication_type")
        self.Communication_type.addItem("")
        self.Communication_type.addItem("")
        self.Communication_type.addItem("")
        self.gridLayout.addWidget(self.Communication_type, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 1)
        self.checkBox_suppressposmsg = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_suppressposmsg.setObjectName("checkBox_suppressposmsg")
        self.gridLayout.addWidget(self.checkBox_suppressposmsg, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.Control_Type = QtWidgets.QComboBox(self.layoutWidget)
        self.Control_Type.setMinimumSize(QtCore.QSize(220, 0))
        self.Control_Type.setMaximumSize(QtCore.QSize(300, 16777215))
        self.Control_Type.setObjectName("Control_Type")
        self.Control_Type.addItem("")
        self.Control_Type.addItem("")
        self.Control_Type.addItem("")
        self.Control_Type.addItem("")
        self.Control_Type.addItem("")
        self.Control_Type.addItem("")
        self.gridLayout.addWidget(self.Control_Type, 0, 1, 1, 1)
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout.addWidget(self.label_ResType, 5, 1, 1, 1)
        self.pushButton_Send28Req = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send28Req.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send28Req.setObjectName("pushButton_Send28Req")
        self.gridLayout.addWidget(self.pushButton_Send28Req, 0, 3, 1, 1)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout.addWidget(self.textBrowser_Resp, 7, 1, 1, 2)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 7, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout.addWidget(self.pushButton_clearLog, 3, 2, 1, 1)
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout.addWidget(self.pushButton_appendLog, 3, 3, 1, 1)
        self.textBrowser_Resp.raise_()
        self.label.raise_()
        self.pushButton_reset.raise_()
        self.label_3.raise_()
        self.pushButton_Send28Req.raise_()
        self.checkBox_suppressposmsg.raise_()
        self.label_ResType.raise_()
        self.label_2.raise_()
        self.lineEdit_NIN.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.Communication_type.raise_()
        self.Control_Type.raise_()
        self.pushButton_clearLog.raise_()
        self.pushButton_appendLog.raise_()
        self.label_status = QtWidgets.QLabel(Form_SID28)
        self.label_status.setGeometry(QtCore.QRect(30, 470, 681, 71))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        
        self.lineEdit_NIN.hide()
        self.label_4.hide()
        self.Control_Type.currentIndexChanged.connect(self.toggle_line_edit)

        self.retranslateUi(Form_SID28)
        QtCore.QMetaObject.connectSlotsByName(Form_SID28)


    # Function to show/hide lineEdit based on dropdown selection
    def toggle_line_edit(self, index):
        if index == 4 or index==5:  # Option 2 selected (index 1)
            self.lineEdit_NIN.show()
            self.label_4.show()
        else:  # Option 1 selected (index 0)
            self.lineEdit_NIN.hide()
            self.label_4.hide()
            #self.label_4.hide()


    def retranslateUi(self, Form_SID28):
        _translate = QtCore.QCoreApplication.translate
        Form_SID28.setWindowTitle(_translate("Form_SID28", "Communication Control Service 28"))
        self.label_5.setText(_translate("Form_SID28", "Comm Type"))
        self.lineEdit_NIN.setToolTip(_translate("Form_SID28", "<html><head/><body><p>Enter Node Identification Number in hexadecimal format</p></body></html>"))
        self.label_4.setText(_translate("Form_SID28", "NIN"))
        self.Communication_type.setToolTip(_translate("Form_SID28", "<html><head/><body><p>Select the Communication type to which you want ECU to move. </p><p>If your Communication type is not in list then contact admin</p></body></html>"))
        self.Communication_type.setItemText(0, _translate("Form_SID28", "01 - Normal communication"))
        self.Communication_type.setItemText(1, _translate("Form_SID28", "02 - Network Management"))
        self.Communication_type.setItemText(2, _translate("Form_SID28", "03 - Normal comm and network management"))
        self.label_2.setText(_translate("Form_SID28", "Response Type"))
        self.label_3.setText(_translate("Form_SID28", "Response"))
        self.checkBox_suppressposmsg.setToolTip(_translate("Form_SID28", "If selected then Suppress Positive Response Message Indication bit will be set in Subfunction"))
        self.checkBox_suppressposmsg.setText(_translate("Form_SID28", "SPRMIB"))
        self.Control_Type.setToolTip(_translate("Form_SID28", "<html><head/><body><p>Select the Control type to which you want ECU to move. <br/>If your control type is not in list then contact admin</p></body></html>"))
        self.Control_Type.setItemText(0, _translate("Form_SID28", "00 - Enable Rx and Tx"))
        self.Control_Type.setItemText(1, _translate("Form_SID28", "01 - Enable Rx and Disable Tx"))
        self.Control_Type.setItemText(2, _translate("Form_SID28", "02 - Disable Rx and Enable Tx"))
        self.Control_Type.setItemText(3, _translate("Form_SID28", "03 - Disable Rx and Tx"))
        self.Control_Type.setItemText(4, _translate("Form_SID28", "04 - Enable Rx and Disable Tx with Address Info"))
        self.Control_Type.setItemText(5, _translate("Form_SID28", "05 - Enable Rx and Tx  with Address Info"))
        self.label_ResType.setText(_translate("Form_SID28", "No Response"))
        self.pushButton_Send28Req.setToolTip(_translate("Form_SID28", "Sends the 28 service request to ECU"))
        self.pushButton_Send28Req.setText(_translate("Form_SID28", "Send Request"))
        self.pushButton_reset.setText(_translate("Form_SID28", "Reset"))
        self.label.setText(_translate("Form_SID28", "Control Type"))
        self.pushButton_clearLog.setText(_translate("Form_SID28", "Clear Log"))
        self.pushButton_appendLog.setText(_translate("Form_SID28", "Add to Log"))
        self.label_status.setText(_translate("Form_SID28", "No Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SID28 = QtWidgets.QDialog()
    ui = Ui_Form_SID28()
    ui.setupUi(Form_SID28)
    Form_SID28.show()
    sys.exit(app.exec_())
