# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Data_transfer.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_form_sid36(object):
    def setupUi(self, Ui_form_sid36):
        Ui_form_sid36.setObjectName("Ui_form_sid36")
        Ui_form_sid36.resize(805, 569)
        self.progressBar = QtWidgets.QProgressBar(Ui_form_sid36)
        self.progressBar.setGeometry(QtCore.QRect(110, 20, 671, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.layoutWidget = QtWidgets.QWidget(Ui_form_sid36)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 50, 761, 411))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_clearLog_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog_2.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog_2.setObjectName("pushButton_clearLog_2")
        self.gridLayout_2.addWidget(self.pushButton_clearLog_2, 1, 2, 1, 1)
        self.pushButton_reset_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset_2.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset_2.setObjectName("pushButton_reset_2")
        self.gridLayout_2.addWidget(self.pushButton_reset_2, 4, 3, 1, 1)
        self.textBrowser_Resp_2 = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp_2.setObjectName("textBrowser_Resp_2")
        self.gridLayout_2.addWidget(self.textBrowser_Resp_2, 4, 1, 1, 2)
        self.label_ResType_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType_2.setAutoFillBackground(False)
        self.label_ResType_2.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType_2.setObjectName("label_ResType_2")
        self.gridLayout_2.addWidget(self.label_ResType_2, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.pushButton_appendLog_2 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog_2.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog_2.setObjectName("pushButton_appendLog_2")
        self.gridLayout_2.addWidget(self.pushButton_appendLog_2, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_status = QtWidgets.QLabel(Ui_form_sid36)
        self.label_status.setGeometry(QtCore.QRect(20, 470, 761, 81))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.label_6 = QtWidgets.QLabel(Ui_form_sid36)
        self.label_6.setGeometry(QtCore.QRect(20, 20, 81, 28))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(Ui_form_sid36)
        QtCore.QMetaObject.connectSlotsByName(Ui_form_sid36)

    def retranslateUi(self, Ui_form_sid36):
        _translate = QtCore.QCoreApplication.translate
        Ui_form_sid36.setWindowTitle(_translate("Ui_form_sid36", "Data_transfer_service36"))
        self.pushButton_clearLog_2.setText(_translate("Ui_form_sid36", "Clear Log"))
        self.pushButton_reset_2.setText(_translate("Ui_form_sid36", "Reset"))
        self.label_ResType_2.setText(_translate("Ui_form_sid36", "No Response"))
        self.label_4.setText(_translate("Ui_form_sid36", "Response : "))
        self.pushButton_appendLog_2.setText(_translate("Ui_form_sid36", "Add to Log"))
        self.label_5.setText(_translate("Ui_form_sid36", "Response Type: "))
        self.label_status.setText(_translate("Ui_form_sid36", "No Status"))
        self.label_6.setText(_translate("Ui_form_sid36", "Progress Bar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_form_sid36 = QtWidgets.QDialog()
    ui = Ui_Ui_form_sid36()
    ui.setupUi(Ui_form_sid36)
    Ui_form_sid36.show()
    sys.exit(app.exec_())
