# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\ass930085\OneDrive - Tata Technologies\Documents\PROXI GIT\reference\ProxiCan\SID_19_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Subfun_SID19(object):
    def setupUi(self, Form_Subfun_SID19):
        Form_Subfun_SID19.setObjectName("Form_Subfun_SID19")
        Form_Subfun_SID19.resize(1363, 759)
        self.layoutWidget = QtWidgets.QWidget(Form_Subfun_SID19)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 100, 1321, 551))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_03 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_03.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_03.setObjectName("pushButton_03")
        self.gridLayout.addWidget(self.pushButton_03, 0, 2, 1, 1)
        self.pushButton_06 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_06.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_06.setObjectName("pushButton_06")
        self.gridLayout.addWidget(self.pushButton_06, 1, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_16.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 7, 0, 1, 1)
        self.pushButton_08 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_08.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_08.setObjectName("pushButton_08")
        self.gridLayout.addWidget(self.pushButton_08, 2, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_12.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 5, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_15.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 6, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_13.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 6, 0, 1, 1)
        self.pushButton_0D = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_0D.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_0D.setObjectName("pushButton_0D")
        self.gridLayout.addWidget(self.pushButton_0D, 4, 0, 1, 1)
        self.pushButton_0F = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_0F.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_0F.setObjectName("pushButton_0F")
        self.gridLayout.addWidget(self.pushButton_0F, 4, 2, 1, 1)
        self.pushButton_0A = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_0A.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_0A.setObjectName("pushButton_0A")
        self.gridLayout.addWidget(self.pushButton_0A, 3, 0, 1, 1)
        self.pushButton_0B = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_0B.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_0B.setObjectName("pushButton_0B")
        self.gridLayout.addWidget(self.pushButton_0B, 3, 1, 1, 1)
        self.pushButton_04 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_04.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_04.setObjectName("pushButton_04")
        self.gridLayout.addWidget(self.pushButton_04, 1, 0, 1, 1)
        self.pushButton_09 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_09.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_09.setObjectName("pushButton_09")
        self.gridLayout.addWidget(self.pushButton_09, 2, 2, 1, 1)
        self.pushButton_0C = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_0C.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_0C.setObjectName("pushButton_0C")
        self.gridLayout.addWidget(self.pushButton_0C, 3, 2, 1, 1)
        self.pushButton_05 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_05.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_05.setObjectName("pushButton_05")
        self.gridLayout.addWidget(self.pushButton_05, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_11.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 5, 1, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_17.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout.addWidget(self.pushButton_17, 7, 1, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_14.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 6, 1, 1, 1)
        self.pushButton_0E = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_0E.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_0E.setObjectName("pushButton_0E")
        self.gridLayout.addWidget(self.pushButton_0E, 4, 1, 1, 1)
        self.pushButton_02 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_02.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(255, 255, 0);\n"
"\n"
"color: rgb(255, 50, 14);")
        self.pushButton_02.setObjectName("pushButton_02")
        self.gridLayout.addWidget(self.pushButton_02, 0, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_18.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout.addWidget(self.pushButton_18, 7, 2, 1, 1)
        self.pushButton_07 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_07.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_07.setObjectName("pushButton_07")
        self.gridLayout.addWidget(self.pushButton_07, 2, 0, 1, 1)
        self.pushButton_01 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_01.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(255, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_01.setObjectName("pushButton_01")
        self.gridLayout.addWidget(self.pushButton_01, 0, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_10.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 5, 0, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_19.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 8, 0, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_42.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout.addWidget(self.pushButton_42, 8, 1, 1, 1)
        self.pushButton_55 = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_55.setStyleSheet("border-color: rgb(255, 8, 251);\n"
"background-color: rgb(252, 255, 0);\n"
"color: rgb(255, 50, 14);")
        self.pushButton_55.setObjectName("pushButton_55")
        self.gridLayout.addWidget(self.pushButton_55, 8, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form_Subfun_SID19)
        self.label.setGeometry(QtCore.QRect(290, 10, 831, 81))
        self.label.setObjectName("label")
        self.label_status = QtWidgets.QLabel(Form_Subfun_SID19)
        self.label_status.setGeometry(QtCore.QRect(20, 660, 1321, 81))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")

        self.retranslateUi(Form_Subfun_SID19)
        QtCore.QMetaObject.connectSlotsByName(Form_Subfun_SID19)

    def retranslateUi(self, Form_Subfun_SID19):
        _translate = QtCore.QCoreApplication.translate
        Form_Subfun_SID19.setWindowTitle(_translate("Form_Subfun_SID19", "Sub-functions for Read DTC Information Servie 19"))
        self.pushButton_03.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x03</p></body></html>"))
        self.pushButton_03.setText(_translate("Form_Subfun_SID19", "Report DTC Snapshot Identification Number 0x03"))
        self.pushButton_06.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x06</p></body></html>"))
        self.pushButton_06.setText(_translate("Form_Subfun_SID19", "Report DTC External Data Record by DTC Number 0x06"))
        self.pushButton_16.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x16</p></body></html>"))
        self.pushButton_16.setText(_translate("Form_Subfun_SID19", "Report DTC Ext Data Record By Record Number 0x16"))
        self.pushButton_08.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x08</p></body></html>"))
        self.pushButton_08.setText(_translate("Form_Subfun_SID19", "Report DTC by Severity Mask Record 0x08"))
        self.pushButton_12.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x12</p></body></html>"))
        self.pushButton_12.setText(_translate("Form_Subfun_SID19", "Report Number Of Emissions OBD DTC By Status Mask 0x12"))
        self.pushButton_15.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x15</p></body></html>"))
        self.pushButton_15.setText(_translate("Form_Subfun_SID19", "Report DTC With Permanent Status 0x15"))
        self.pushButton_13.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x13</p></body></html>"))
        self.pushButton_13.setText(_translate("Form_Subfun_SID19", "Report Emissions OBD DTC By Status Mask 0x13"))
        self.pushButton_0D.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x0D</p></body></html>"))
        self.pushButton_0D.setText(_translate("Form_Subfun_SID19", "Report Most Recent Test Failed DTC 0x0D"))
        self.pushButton_0F.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x0F</p></body></html>"))
        self.pushButton_0F.setText(_translate("Form_Subfun_SID19", "Report Mirror Memory DTC by Status Mask 0x0F  "))
        self.pushButton_0A.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x0A</p></body></html>"))
        self.pushButton_0A.setText(_translate("Form_Subfun_SID19", "Report Supported DTC 0x0A"))
        self.pushButton_0B.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x0B</p></body></html>"))
        self.pushButton_0B.setText(_translate("Form_Subfun_SID19", "Report First Test Failed DTC 0x0B"))
        self.pushButton_04.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x04</p></body></html>"))
        self.pushButton_04.setText(_translate("Form_Subfun_SID19", "Report DTC Snapshot Record by DTC Number 0x04"))
        self.pushButton_09.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x09</p></body></html>"))
        self.pushButton_09.setText(_translate("Form_Subfun_SID19", "Report Severity Information of DTC 0x09"))
        self.pushButton_0C.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x0C</p></body></html>"))
        self.pushButton_0C.setText(_translate("Form_Subfun_SID19", "Report First Confirmed DTC 0x0C"))
        self.pushButton_05.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x05</p></body></html>"))
        self.pushButton_05.setText(_translate("Form_Subfun_SID19", "Report DTC Stored Data by Record Number 0x05"))
        self.pushButton_11.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x11</p></body></html>"))
        self.pushButton_11.setText(_translate("Form_Subfun_SID19", "Report Number Of Mirror Memory DTC By Status Mask 0x11"))
        self.pushButton_17.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x17</p></body></html>"))
        self.pushButton_17.setText(_translate("Form_Subfun_SID19", "Report User Def Memory DTC By Status Mask 0x17"))
        self.pushButton_14.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x14</p></body></html>"))
        self.pushButton_14.setText(_translate("Form_Subfun_SID19", "Report DTC Fault Detection Counter 0x14"))
        self.pushButton_0E.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x0E</p></body></html>"))
        self.pushButton_0E.setText(_translate("Form_Subfun_SID19", "Report Most Recent Confirmed DTC 0x0E"))
        self.pushButton_02.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x02</p></body></html>"))
        self.pushButton_02.setText(_translate("Form_Subfun_SID19", "Report DTC by Status Mask 0x02"))
        self.pushButton_18.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x18</p></body></html>"))
        self.pushButton_18.setText(_translate("Form_Subfun_SID19", "Report User Def Memory DTC Snapshot Record By DTC Number 0x18"))
        self.pushButton_07.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x07</p></body></html>"))
        self.pushButton_07.setText(_translate("Form_Subfun_SID19", "Report Number of DTC by Severity Mask Record 0x07"))
        self.pushButton_01.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x01</p></body></html>"))
        self.pushButton_01.setText(_translate("Form_Subfun_SID19", "Report Number of DTC by Status Mask 0x01"))
        self.pushButton_10.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x10</p></body></html>"))
        self.pushButton_10.setText(_translate("Form_Subfun_SID19", "Report Mirror Memory DTC Ext Data Record By DTC Number 0x10"))
        self.pushButton_19.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x19</p></body></html>"))
        self.pushButton_19.setText(_translate("Form_Subfun_SID19", "Report User Def Memory DTC Ext Data Record By DTC Number 0x19"))
        self.pushButton_42.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x42</p></body></html>"))
        self.pushButton_42.setText(_translate("Form_Subfun_SID19", "Report WWH OBD DTC By Mask Record 0x42"))
        self.pushButton_55.setToolTip(_translate("Form_Subfun_SID19", "<html><head/><body><p>Opens the subfunction window 0x55</p></body></html>"))
        self.pushButton_55.setText(_translate("Form_Subfun_SID19", "Report WWH OBD DTC With Permanent Status 0x55"))
        self.label.setText(_translate("Form_Subfun_SID19", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600; text-decoration: underline; color:#0000ff;\">Select the Sub-function for Service 19 to be Requested</span></p></body></html>"))
        self.label_status.setText(_translate("Form_Subfun_SID19", "No Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SID_19 = QtWidgets.QWidget()
    ui = Ui_Form_Subfun_SID19()
    ui.setupUi(Form_SID_19)
    Form_SID_19.show()
    sys.exit(app.exec_())