# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SID_22.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID22(object):
    def setupUi(self, Form_SID22):
        Form_SID22.setObjectName("Form_SID22")
        Form_SID22.resize(611, 495)
        Form_SID22.setMinimumSize(QtCore.QSize(400, 400))
        self.label_status = QtWidgets.QLabel(Form_SID22)
        self.label_status.setGeometry(QtCore.QRect(10, 430, 591, 51))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.layoutWidget = QtWidgets.QWidget(Form_SID22)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 591, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout.addWidget(self.label_ResType, 1, 1, 1, 1)
        self.lineEdit_DID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_DID.setObjectName("lineEdit_DID")
        self.gridLayout.addWidget(self.lineEdit_DID, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout.addWidget(self.textBrowser_Resp, 4, 1, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout.addWidget(self.pushButton_clearLog, 1, 2, 1, 1)
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout.addWidget(self.pushButton_appendLog, 1, 3, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 4, 3, 1, 1)
        self.pushButton_Send22Req = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send22Req.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send22Req.setObjectName("pushButton_Send22Req")
        self.gridLayout.addWidget(self.pushButton_Send22Req, 0, 2, 1, 2)

        self.retranslateUi(Form_SID22)
        QtCore.QMetaObject.connectSlotsByName(Form_SID22)

    def retranslateUi(self, Form_SID22):
        _translate = QtCore.QCoreApplication.translate
        Form_SID22.setWindowTitle(_translate("Form_SID22", "Read Data By Identifier Service 22"))
        self.label_status.setText(_translate("Form_SID22", "No Status"))
        self.label_ResType.setText(_translate("Form_SID22", "No Response"))
        self.lineEdit_DID.setToolTip(_translate("Form_SID22", "<html><head/><body><p>Enter Data Identifier in hexadecimal format</p></body></html>"))
        self.label_3.setText(_translate("Form_SID22", "Response : "))
        self.label_2.setText(_translate("Form_SID22", "Response Type: "))
        self.label.setText(_translate("Form_SID22", "DID"))
        self.pushButton_clearLog.setText(_translate("Form_SID22", "Clear Log"))
        self.pushButton_appendLog.setText(_translate("Form_SID22", "Add to Log"))
        self.pushButton_reset.setText(_translate("Form_SID22", "Reset"))
        self.pushButton_Send22Req.setToolTip(_translate("Form_SID22", "Sends the 22 service request to ECU"))
        self.pushButton_Send22Req.setText(_translate("Form_SID22", "Send Request"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SID22 = QtWidgets.QWidget()
    ui = Ui_Form_SID22()
    ui.setupUi(Form_SID22)
    Form_SID22.show()
    sys.exit(app.exec_())
