# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wdbi_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID2E(object):
    def setupUi(self, Form_SID2E):
        Form_SID2E.setObjectName("Form_SID2E")
        Form_SID2E.resize(607, 511)
        Form_SID2E.setMinimumSize(QtCore.QSize(400, 400))
        self.label_status = QtWidgets.QLabel(Form_SID2E)
        self.label_status.setGeometry(QtCore.QRect(10, 430, 591, 71))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")
        self.layoutWidget = QtWidgets.QWidget(Form_SID2E)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 591, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout.addWidget(self.pushButton_appendLog, 2, 3, 1, 1)
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout.addWidget(self.label_ResType, 2, 1, 1, 1)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout.addWidget(self.textBrowser_Resp, 5, 1, 1, 2)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout.addWidget(self.pushButton_clearLog, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 5, 3, 1, 1)
        self.lineEdit_DID = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_DID.setObjectName("lineEdit_DID")
        self.gridLayout.addWidget(self.lineEdit_DID, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.pushButton_Send2EReq = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send2EReq.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send2EReq.setObjectName("pushButton_Send2EReq")
        self.gridLayout.addWidget(self.pushButton_Send2EReq, 0, 2, 1, 2)
        self.lineEdit_DataValue = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_DataValue.setObjectName("lineEdit_DataValue")
        self.gridLayout.addWidget(self.lineEdit_DataValue, 1, 1, 1, 3)

        self.retranslateUi(Form_SID2E)
        QtCore.QMetaObject.connectSlotsByName(Form_SID2E)

    def retranslateUi(self, Form_SID2E):
        _translate = QtCore.QCoreApplication.translate
        Form_SID2E.setWindowTitle(_translate("Form_SID2E", "Write Data By Identifier Service 2E"))
        self.label_status.setText(_translate("Form_SID2E", "No Status"))
        self.pushButton_appendLog.setText(_translate("Form_SID2E", "Add to Log"))
        self.label_ResType.setText(_translate("Form_SID2E", "No Response"))
        self.pushButton_clearLog.setText(_translate("Form_SID2E", "Clear Log"))
        self.label_4.setText(_translate("Form_SID2E", "Data Value"))
        self.label.setText(_translate("Form_SID2E", "DID"))
        self.pushButton_reset.setText(_translate("Form_SID2E", "Reset"))
        self.label_3.setText(_translate("Form_SID2E", "Response : "))
        self.label_2.setText(_translate("Form_SID2E", "Response Type: "))
        self.pushButton_Send2EReq.setToolTip(_translate("Form_SID2E", "Sends the 22 service request to ECU"))
        self.pushButton_Send2EReq.setText(_translate("Form_SID2E", "Send Request"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SID2E = QtWidgets.QWidget()
    ui = Ui_Form_SID2E()
    ui.setupUi(Form_SID2E)
    Form_SID2E.show()
    sys.exit(app.exec_())
