# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SID_11.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID11(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(698, 531)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 80, 621, 302))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout.addWidget(self.pushButton_appendLog, 3, 3, 1, 1)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout.addWidget(self.textBrowser_Resp, 6, 1, 1, 2)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout.addWidget(self.pushButton_clearLog, 3, 2, 1, 1)
        self.comboBox_ECUReset = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_ECUReset.setMinimumSize(QtCore.QSize(220, 0))
        self.comboBox_ECUReset.setMaximumSize(QtCore.QSize(220, 16777215))
        self.comboBox_ECUReset.setObjectName("comboBox_ECUReset")
        self.comboBox_ECUReset.addItem("")
        self.comboBox_ECUReset.addItem("")
        self.comboBox_ECUReset.addItem("")
        self.gridLayout.addWidget(self.comboBox_ECUReset, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout.addWidget(self.label_ResType, 3, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(130, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 6, 0, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout.addWidget(self.pushButton_reset, 6, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton_Send11Req = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send11Req.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send11Req.setObjectName("pushButton_Send11Req")
        self.gridLayout.addWidget(self.pushButton_Send11Req, 0, 3, 1, 1)
        self.checkBox_suppressposmsg = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_suppressposmsg.setObjectName("checkBox_suppressposmsg")
        self.gridLayout.addWidget(self.checkBox_suppressposmsg, 0, 2, 1, 1, QtCore.Qt.AlignRight)
        self.pushButton_appendLog.raise_()
        self.label_ResType.raise_()
        self.textBrowser_Resp.raise_()
        self.pushButton_clearLog.raise_()
        self.label.raise_()
        self.pushButton_reset.raise_()
        self.label_3.raise_()
        self.pushButton_Send11Req.raise_()
        self.comboBox_ECUReset.raise_()
        self.label_2.raise_()
        self.checkBox_suppressposmsg.raise_()
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setGeometry(QtCore.QRect(50, 400, 621, 71))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_appendLog.setText(_translate("Dialog", "Add to Log"))
        self.pushButton_clearLog.setText(_translate("Dialog", "Clear Log"))
        self.comboBox_ECUReset.setToolTip(_translate("Dialog", "Select the Reset Type to which you want ECU to reset. If your reset type is not in list then contact admin"))
        self.comboBox_ECUReset.setItemText(0, _translate("Dialog", "01 - Hard reset"))
        self.comboBox_ECUReset.setItemText(1, _translate("Dialog", "02 - KeyOffOn reset"))
        self.comboBox_ECUReset.setItemText(2, _translate("Dialog", "03 - Soft reset"))
        self.label_ResType.setText(_translate("Dialog", "No Response"))
        self.label_2.setText(_translate("Dialog", "Response Type"))
        self.label_3.setText(_translate("Dialog", "Response"))
        self.pushButton_reset.setText(_translate("Dialog", "Reset"))
        self.label.setText(_translate("Dialog", "Reset Type"))
        self.pushButton_Send11Req.setToolTip(_translate("Dialog", "Sends the 11 service request to ECU"))
        self.pushButton_Send11Req.setText(_translate("Dialog", "Send Request"))
        self.checkBox_suppressposmsg.setToolTip(_translate("Dialog", "If selected then Suppress Positive Response Message Indication bit will be set in Subfunction"))
        self.checkBox_suppressposmsg.setText(_translate("Dialog", "SPRMIB"))
        self.label_status.setText(_translate("Dialog", "No Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Form_SID11()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
