# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SID_31.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_SID_31(object):
    def setupUi(self, Form_SID_31):
        Form_SID_31.setObjectName("Form_SID_31")
        Form_SID_31.resize(624, 495)
        self.layoutWidget = QtWidgets.QWidget(Form_SID_31)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 599, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_StatusRecord = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_StatusRecord.setObjectName("checkBox_StatusRecord")
        self.gridLayout_2.addWidget(self.checkBox_StatusRecord, 1, 2, 1, 1)
        self.pushButton_reset = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_reset.setStyleSheet("background-color: rgb(170, 170, 0);\n"
"font: 75 8pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 85, 0);")
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.gridLayout_2.addWidget(self.pushButton_reset, 6, 3, 1, 1)
        self.label_ResType = QtWidgets.QLabel(self.layoutWidget)
        self.label_ResType.setAutoFillBackground(False)
        self.label_ResType.setStyleSheet("color: rgb(0, 0, 255);")
        self.label_ResType.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ResType.setObjectName("label_ResType")
        self.gridLayout_2.addWidget(self.label_ResType, 3, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 3, 0, 1, 1)
        self.textBrowser_Resp = QtWidgets.QTextBrowser(self.layoutWidget)
        self.textBrowser_Resp.setObjectName("textBrowser_Resp")
        self.gridLayout_2.addWidget(self.textBrowser_Resp, 6, 1, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_RoutineIdentifier = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_RoutineIdentifier.setObjectName("lineEdit_RoutineIdentifier")
        self.gridLayout_2.addWidget(self.lineEdit_RoutineIdentifier, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 1)
        self.pushButton_clearLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_clearLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_clearLog.setObjectName("pushButton_clearLog")
        self.gridLayout_2.addWidget(self.pushButton_clearLog, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.pushButton_Send31Req = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Send31Req.setStyleSheet("background-color: rgb(0, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(0, 0, 0);")
        self.pushButton_Send31Req.setObjectName("pushButton_Send31Req")
        self.gridLayout_2.addWidget(self.pushButton_Send31Req, 0, 2, 1, 2)
        self.pushButton_appendLog = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_appendLog.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"color: rgb(85, 0, 0);")
        self.pushButton_appendLog.setObjectName("pushButton_appendLog")
        self.gridLayout_2.addWidget(self.pushButton_appendLog, 3, 3, 1, 1)
        self.Subfunction = QtWidgets.QComboBox(self.layoutWidget)
        self.Subfunction.setMinimumSize(QtCore.QSize(220, 0))
        self.Subfunction.setMaximumSize(QtCore.QSize(300, 16777215))
        self.Subfunction.setObjectName("Subfunction")
        self.Subfunction.addItem("")
        self.Subfunction.addItem("")
        self.Subfunction.addItem("")
        self.gridLayout_2.addWidget(self.Subfunction, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 0, 1, 1)
        self.lineEdit_StatusRecord = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_StatusRecord.setObjectName("lineEdit_StatusRecord")
        self.gridLayout_2.addWidget(self.lineEdit_StatusRecord, 2, 1, 1, 1)
        self.checkBox_suppressposmsg = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_suppressposmsg.setObjectName("checkBox_suppressposmsg")
        self.gridLayout_2.addWidget(self.checkBox_suppressposmsg, 1, 3, 1, 1)
        self.label_status = QtWidgets.QLabel(Form_SID_31)
        self.label_status.setGeometry(QtCore.QRect(10, 420, 591, 51))
        self.label_status.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"color: rgb(85, 0, 0);\n"
"border-color: rgb(0, 0, 255);")
        self.label_status.setAlignment(QtCore.Qt.AlignCenter)
        self.label_status.setWordWrap(True)
        self.label_status.setObjectName("label_status")

        self.label_7.hide()
        self.lineEdit_StatusRecord.hide()
        self.checkBox_StatusRecord.stateChanged.connect(self.toggleStatusRecord)

        self.retranslateUi(Form_SID_31)
        QtCore.QMetaObject.connectSlotsByName(Form_SID_31)

    def toggleStatusRecord(self, state):
        # Show the line edit only if the checkbox is checked
        self.lineEdit_StatusRecord.setVisible(state == QtCore.Qt.Checked)
        self.label_7.setVisible(state == QtCore.Qt.Checked)

    def retranslateUi(self, Form_SID_31):
        _translate = QtCore.QCoreApplication.translate
        Form_SID_31.setWindowTitle(_translate("Form_SID_31", "Routine Control service 31"))
        self.checkBox_StatusRecord.setToolTip(_translate("Form_SID_31", "<html><head/><body><p>Click to enable the field to enter Option Record</p></body></html>"))
        self.checkBox_StatusRecord.setText(_translate("Form_SID_31", "Option Record"))
        self.pushButton_reset.setText(_translate("Form_SID_31", "Reset"))
        self.label_ResType.setText(_translate("Form_SID_31", "No Response"))
        self.label_5.setText(_translate("Form_SID_31", "Response Type: "))
        self.label_9.setText(_translate("Form_SID_31", "Sub Function"))
        self.lineEdit_RoutineIdentifier.setToolTip(_translate("Form_SID_31", "<html><head/><body><p>Enter the Routine Identifier in hexadecimal format</p></body></html>"))
        self.label_4.setText(_translate("Form_SID_31", "Response : "))
        self.pushButton_clearLog.setText(_translate("Form_SID_31", "Clear Log"))
        self.label_6.setText(_translate("Form_SID_31", "Routine Identifier"))
        self.pushButton_Send31Req.setToolTip(_translate("Form_SID_31", "Sends the 31 service request to ECU"))
        self.pushButton_Send31Req.setText(_translate("Form_SID_31", "Send Request"))
        self.pushButton_appendLog.setText(_translate("Form_SID_31", "Add to Log"))
        self.Subfunction.setToolTip(_translate("Form_SID_31", "<html><head/><body><p>Select the Routine type to which you want ECU to move. </p><p>If your routine type is not in list then contact admin</p></body></html>"))
        self.Subfunction.setItemText(0, _translate("Form_SID_31", "01 - Start Routine"))
        self.Subfunction.setItemText(1, _translate("Form_SID_31", "02 - Stop Routine"))
        self.Subfunction.setItemText(2, _translate("Form_SID_31", "03 - Request Routine Results"))
        self.label_7.setText(_translate("Form_SID_31", "Option Record"))
        self.lineEdit_StatusRecord.setToolTip(_translate("Form_SID_31", "<html><head/><body><p>Enter the Status Record in Hexadecimal format</p><p><br/></p></body></html>"))
        self.checkBox_suppressposmsg.setToolTip(_translate("Form_SID_31", "If selected then Suppress Positive Response Message Indication bit will be set in Subfunction"))
        self.checkBox_suppressposmsg.setText(_translate("Form_SID_31", "SPRMIB"))
        self.label_status.setText(_translate("Form_SID_31", "No Status"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_SID_31 = QtWidgets.QDialog()
    ui = Ui_Form_SID_31()
    ui.setupUi(Form_SID_31)
    Form_SID_31.show()
    sys.exit(app.exec_())
